{% set version = "1.3.6" %}

package:
  name: blist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blist/blist-{{ version }}.tar.gz
  sha256: 3a12c450b001bdf895b30ae818d4d6d3f1552096b8c995f0fe0c74bef04d1fc3
  patches:
    - patches/0001-remove-obsolete-if-guards-that-confuse-MSVC.patch
    - patches/0002-also-install-blist.test.patch
    - patches/0003-make-__iter__-PEP-479-compatible.patch
    - patches/0004-compatibility-with-PEP-620.patch

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - blist
  source_files:
    # must declare test script (not packaged in blist itself)
    - test_blist.py
  commands:
    # running this needs patch 0002, otherwise blist.test cannot be imported
    - python test_blist.py

about:
  home: https://github.com/DanielStutzbach/blist
  # The license does not mention BSD, but it is the same as: https://opensource.org/licenses/BSD-3-Clause
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A list-like type with better asymptotic performance and similar performance on small lists '

  description: |
    The blist is a drop-in replacement for the Python list that provides better performance
    when modifying large lists. The blist package also provides sortedlist, sortedset,
    weaksortedlist, weaksortedset, sorteddict, and btuple types.
  doc_url: http://stutzbachenterprises.com/blist/
  dev_url: https://github.com/DanielStutzbach/blist

extra:
  recipe-maintainers:
    - h-vetinari
